
[[collectd2http]]
name = "example-collectd2http"
bind-addr = "127.1.1.1:25826"
read-buffer = 0 # default
typesdb = "/usr/share/collectd/types.db"
output = [
    { name="local1", location = "http://127.0.0.1:8086/write?db=shard1" },
    { name="local2", location = "http://127.0.0.1:8086/write?db=shard2" },
]
